name: HabotConnect CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Application and Infrastructure
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework

      - name: Run Django system check
        run: |
          python manage.py check

      - name: Run Django tests
        run: |
          python manage.py test

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.8"

      - name: Terraform Format Check
        working-directory: student_onboarding/terraform
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: student_onboarding/terraform
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: student_onboarding/terraform
        run: terraform validate

      # - name: Terraform Plan
      #   working-directory: student_onboarding/terraform
      #   env:
      #     TF_VAR_iam_user_email: ci-validation@example.com
      #   run: terraform plan -input=false -lock=false

      - name: Security Scan - Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: student_onboarding/terraform
          framework: terraform
          soft_fail: false
          skip_check: CKV_GCP_80,CKV_GCP_81,CKV_GCP_62

      - name: Remove Checkov SARIF file
        if: always()
        run: sudo rm -f results.sarif

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t mimansha0501/habotconnect:v1 .

      - name: Push Docker Image
        run: docker push mimansha0501/habotconnect:v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::673044266492:role/HabotConnect-GitHub-Actions-Role
          aws-region: ap-south-1
      - name: Deploy to AWS EC2 using SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-0703ebf369be19957" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["sudo docker pull mimansha0501/habotconnect:v1","sudo docker stop habotconnect-app || true","sudo docker rm habotconnect-app || true","sudo docker run -d --name habotconnect-app --restart unless-stopped -p 8000:8000 mimansha0501/habotconnect:v1"]' \
            --query "Command.CommandId" \
            --output text)

        echo "SSM Command ID: $COMMAND_ID"

        aws ssm wait command-executed \
         --command-id "$COMMAND_ID" \
         --instance-id "i-0703ebf369be19957"

        aws ssm get-command-invocation \
          --command-id "$COMMAND_ID" \
          --instance-id "i-0703ebf369be19957"

      - name: Secret Scan - Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}